apiVersion: v1
baseDomain: ocp431.example.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: lab
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: ocp43-1
    region: us-east1
publish: Internal
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3lVUg==","email":"test@redhat.com"},"registry.connect.redhat.com":{"auth":"NTEQ==","email":"test@redhat.com"},"registry.redhat.io":{"auth":"NTE==","email":"test@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkoQVSP4mJVO4CkxZjP+blohvFGPBXJOZC2Yrw== ocp@bastion.ocp4.example.com
